__Example 1__

In [2]:
# Example code for initializing NumPy array
import numpy as np

# Create a rank 1 array
a = np.array([0, 1, 2])
print (type(a))
print(np.ndim(a))
print(a.shape)

<class 'numpy.ndarray'>
1
(3,)


In [4]:
# Create a rank 2 array
a = np.array([[0, 1, 2],[3,4,5]])
print (type(a))
print(np.ndim(a))
print(a.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [5]:
# Change an element of the array
a[0][0] = 6
print(a)


[[6 1 2]
 [3 4 5]]


In [6]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create a 3x3 identity matrix
e = np.eye(3)
print(e)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Create a 3x3 constant array
c = np.full((3,3), 7)
print(c)


[[7 7 7]
 [7 7 7]
 [7 7 7]]



__Example 2: Shape and reshaping of Numpy Array__

In [9]:
a = np.array([11,12,13,14,15,16])
a.shape

(6,)

In [10]:
a.reshape([2,3])


array([[11, 12, 13],
       [14, 15, 16]])

In [11]:
a.reshape([3,2])


array([[11, 12],
       [13, 14],
       [15, 16]])

__Example 3: Numpy Datatypes__

In [12]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int32)
print (x.dtype, y.dtype, z.dtype)


int64 float64 int32


__Example 4:Basic Slicing:__  
NumPy arrays can be sliced, similar to lists. You must specify a slice for each dimension of the array as the arrays may be multidimensional.  
The basic slice syntax is i: j: k, where i is the starting index, j is the stopping index, and k is the step and k is not equal to 0


In [15]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [16]:
x[-3:3:-1]


array([7, 6, 5, 4])

In [17]:
x[-2:10]

array([8, 9])

__Example 5:Advanced Indexing__

In [6]:
a=np.array([[1,2,3], [3, 4, 5], [5, 6,7]])
# Find the elements of a that are bigger than 2
print (a > 2)
print(a.shape)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
(3, 3)


In [19]:
# to get the actual value
print (a[a >2] )

[3 4 5 6]


  
__Example 6: Array Math__

In [20]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
# Elementwise sum; both produce the array
print(x+y)



[[ 8 10]
 [12 14]
 [16 18]]


In [21]:
print(np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]


In [22]:
#Sum function (2D Array)
x=np.array([[1,2],[3,4]])
# Compute sum of all elements
print (np.sum(x))
# Compute sum of each column
print (np.sum(x, axis=0))
# Compute sum of each row
print (np.sum(x, axis=1))


10
[4 6]
[3 7]


In [25]:
#Sum function (3 Dim)
x=np.array([[[1,2],[3,4]],[[1,2],[3,5]] ])
print(x.shape)
print(np.ndim(x))
# Compute sum of all elements
print(np.sum(x))
# Compute sum of each column
print (np.sum(x, axis=0))
# Compute sum of each row
print (np.sum(x, axis=1))

print (np.sum(x, axis=2))


(2, 2, 2)
3
21
[[2 4]
 [6 9]]
[[4 6]
 [4 7]]
[[3 7]
 [3 8]]


__Example 7: Numpy Speed demo__

In [26]:
#Numpy Speed

import numpy as np
import time
import sys
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
# numpy array
start= time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)



python list took:  221.36640548706055
numpy took:  23.36287498474121
