In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)


[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


__TEST/TRAIN SPLIT EXAMPLE__

In [3]:
from sklearn.model_selection import ShuffleSplit
import numpy as np
X = np.arange(10)
ss = ShuffleSplit(n_splits=5, test_size=0.25,random_state=0)
for train_index, test_index in ss.split(X):
    print("%s %s" % (train_index, test_index))



[9 1 6 7 3 0 5] [2 8 4]
[2 9 8 0 6 7 4] [3 5 1]
[4 5 1 0 6 9 7] [2 3 8]
[2 7 5 8 0 3 4] [6 1 9]
[4 1 0 6 8 9 3] [5 2 7]


__SIMPLE LINEAR MODEL__

In [6]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit([[1],[2],[3]],[1,2,3])


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
regr.predict([[4],[7]])

array([4., 7.])

__Another Example__

In [8]:
import pandas as pd
df = pd.read_csv('./Employees.csv')

In [9]:
df.head(n=10)

Employee Name  Employee ID  Age Department Location  Experience  \
0  Gabrielle Smith     82036322   30         5G       L5         4.0   
1    Nathan Howard     57825244   25         5G       M2         3.0   
2    Yvonne Wilson     67211472   27         5G       M2         3.6   
3    Alison Greene     57816451   27         5G       L5         6.4   
4   Dominic Turner     57819904   26         5G       L6         5.9   
5     Ella Simpson     57887284   30         5G       L5         8.0   
6     Harry McLean     67249809   28         5G       L5         6.0   
7    Joshua Hunter     57823797   28         5G       E2         7.0   
8  Caroline Graham     57144516   34         5G       L5        10.0   
9     Piers Arnold     57780544   35         5G       L5         9.3   

             Role   ML Python  Salary  
0        Engineer   No    Yes    26.0  
1        Engineer   No    Yes    24.0  
2        Engineer  Yes    Yes    24.2  
3        Engineer   No    Yes    32.8  
4        Engineer   No    Yes    32.8  
5  Technical Lead  Yes    Yes    36.0  
6  Technical Lead   No    Yes    32.0  
7  Technical Lead  Yes    Yes    34.0  
8        Engineer   No    Yes    46.0  
9  Technical Lead  Yes    Yes    44.6

In [15]:
df[['Experience']]
regr.fit(df[['Experience']], df['Salary'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
regr.predict(df[['Experience']].head(n=5))

array([27.09068011, 24.1135473 , 25.89982699, 34.23579887, 32.74723246])

In [19]:
regr.predict([[1]])

array([18.15928167])